//This is for ai profiles generated by AI
const CalendarIntegration = (sequelize, Sequelize) => {
  const CalIntegration = sequelize.define("CalendarIntegration", {
    type: {
      type: Sequelize.STRING,
      defaultValue: "cal_dot_com", // "cal_dot_com", "ghl"
    },
    eventId: {
      //Event id is the meeting event on cal.com
      type: Sequelize.STRING,
      allowNull: true,
    },
    apiKey: {
      type: Sequelize.STRING,
      allowNull: false,
    },
    actionId: {
      type: Sequelize.STRING, // id of the action on the synthflow
      allowNull: true,
    },
    userId: {
      type: Sequelize.INTEGER,
      allowNull: true,
      references: {
        model: "Users", //
        key: "id",
      },
    },
  });

  return CalIntegration;
};

export default CalendarIntegration;

export const CalendarIntegrationTypes = {
  CalDotCom: "cal_dot_com",
  Ghl: "ghl",
  Google: "google",
  Calendly: "Calendly",
};
