//This is for ai profiles generated by AI
const GhlCalendarModel = (sequelize, Sequelize) => {
  const GhlCalendarModel = sequelize.define("GhlCalendarModel", {
    calendarName: {
      type: Sequelize.STRING,
      defaultValue: "",
    },
    ghlCalendarId: {
      //Event id is the meeting event on cal.com
      type: Sequelize.STRING,
      allowNull: true,
    },
    slug: {
      type: Sequelize.STRING,
      allowNull: true,
    },
    link: {
      type: Sequelize.STRING,
      allowNull: true,
    },
    actionId: {
      type: Sequelize.STRING, // id of the action on the synthflow
      allowNull: true,
    },
    mainAgentId: {
      type: Sequelize.INTEGER,
      allowNull: true,
      references: {
        model: "MainAgentModels",
        key: "id",
      },
      onDelete: "CASCADE",
      onUpdate: "CASCADE",
    },
    userId: {
      type: Sequelize.INTEGER,
      allowNull: true,
      references: {
        model: "Users", //
        key: "id",
      },
    },
  });

  return GhlCalendarModel;
};

export default GhlCalendarModel;
