export const AreaCodes = {
  201: { city: "Jersey City", state: "New Jersey" },
  202: { city: "Washington", state: "District of Columbia" },
  203: { city: "Bridgeport", state: "Connecticut" },
  205: { city: "Birmingham", state: "Alabama" },
  206: { city: "Seattle", state: "Washington" },
  207: { city: "Portland", state: "Maine" },
  208: { city: "Boise", state: "Idaho" },
  209: { city: "Stockton", state: "California" },
  210: { city: "San Antonio", state: "Texas" },
  212: { city: "New York City", state: "New York" },
  213: { city: "Los Angeles", state: "California" },
  214: { city: "Dallas", state: "Texas" },
  215: { city: "Philadelphia", state: "Pennsylvania" },
  216: { city: "Cleveland", state: "Ohio" },
  217: { city: "Springfield", state: "Illinois" },
  218: { city: "Duluth", state: "Minnesota" },
  219: { city: "Hammond", state: "Indiana" },
  220: { city: "Newark", state: "Ohio" },
  223: { city: "Lancaster", state: "Pennsylvania" },
  224: { city: "Elgin", state: "Illinois" },
  225: { city: "Baton Rouge", state: "Louisiana" },
  228: { city: "Gulfport", state: "Mississippi" },
  229: { city: "Albany", state: "Georgia" },
  231: { city: "Muskegon", state: "Michigan" },
  234: { city: "Akron", state: "Ohio" },
  239: { city: "Cape Coral", state: "Florida" },
  240: { city: "Germantown", state: "Maryland" },
  248: { city: "Troy", state: "Michigan" },
  251: { city: "Mobile", state: "Alabama" },
  252: { city: "Greenville", state: "North Carolina" },
  253: { city: "Tacoma", state: "Washington" },
  254: { city: "Killeen", state: "Texas" },
  256: { city: "Huntsville", state: "Alabama" },
  260: { city: "Fort Wayne", state: "Indiana" },
  262: { city: "Kenosha", state: "Wisconsin" },
  267: { city: "Philadelphia", state: "Pennsylvania" },
  269: { city: "Kalamazoo", state: "Michigan" },
  270: { city: "Bowling Green", state: "Kentucky" },
  272: { city: "Scranton", state: "Pennsylvania" },
  276: { city: "Bristol", state: "Virginia" },
  281: { city: "Houston", state: "Texas" },
  301: { city: "Germantown", state: "Maryland" },
  302: { city: "Wilmington", state: "Delaware" },
  303: { city: "Denver", state: "Colorado" },
  304: { city: "Charleston", state: "West Virginia" },
  305: { city: "Miami", state: "Florida" },
  307: { city: "Cheyenne", state: "Wyoming" },
  308: { city: "Grand Island", state: "Nebraska" },
  309: { city: "Peoria", state: "Illinois" },
  310: { city: "Los Angeles", state: "California" },
  312: { city: "Chicago", state: "Illinois" },
  313: { city: "Detroit", state: "Michigan" },
  314: { city: "St. Louis", state: "Missouri" },
  315: { city: "Syracuse", state: "New York" },
  316: { city: "Wichita", state: "Kansas" },
  317: { city: "Indianapolis", state: "Indiana" },
  318: { city: "Shreveport", state: "Louisiana" },
  319: { city: "Cedar Rapids", state: "Iowa" },
  320: { city: "St. Cloud", state: "Minnesota" },
  321: { city: "Orlando", state: "Florida" },
  323: { city: "Los Angeles", state: "California" },
  325: { city: "Abilene", state: "Texas" },
  330: { city: "Akron", state: "Ohio" },
  331: { city: "Aurora", state: "Illinois" },
  334: { city: "Montgomery", state: "Alabama" },
  336: { city: "Greensboro", state: "North Carolina" },
  337: { city: "Lafayette", state: "Louisiana" },
  339: { city: "Lynn", state: "Massachusetts" },
  346: { city: "Houston", state: "Texas" },
  347: { city: "New York City", state: "New York" },
  351: { city: "Lynn", state: "Massachusetts" },
  352: { city: "Gainesville", state: "Florida" },
  360: { city: "Vancouver", state: "Washington" },
  361: { city: "Corpus Christi", state: "Texas" },
  364: { city: "Paducah", state: "Kentucky" },
  380: { city: "Columbus", state: "Ohio" },
  385: { city: "Salt Lake City", state: "Utah" },
  386: { city: "Daytona Beach", state: "Florida" },
  401: { city: "Providence", state: "Rhode Island" },
  402: { city: "Omaha", state: "Nebraska" },
  404: { city: "Atlanta", state: "Georgia" },
  405: { city: "Oklahoma City", state: "Oklahoma" },
  406: { city: "Billings", state: "Montana" },
  407: { city: "Orlando", state: "Florida" },
  408: { city: "San Jose", state: "California" },
  409: { city: "Beaumont", state: "Texas" },
  410: { city: "Baltimore", state: "Maryland" },
  412: { city: "Pittsburgh", state: "Pennsylvania" },
  413: { city: "Springfield", state: "Massachusetts" },
  414: { city: "Milwaukee", state: "Wisconsin" },
  415: { city: "San Francisco", state: "California" },
  417: { city: "Springfield", state: "Missouri" },
  419: { city: "Toledo", state: "Ohio" },
  423: { city: "Chattanooga", state: "Tennessee" },
  424: { city: "Santa Monica", state: "California" },
  425: { city: "Bellevue", state: "Washington" },
  430: { city: "Longview", state: "Texas" },
  432: { city: "Midland", state: "Texas" },
  434: { city: "Lynchburg", state: "Virginia" },
  435: { city: "St. George", state: "Utah" },
  440: { city: "Lorain", state: "Ohio" },
  442: { city: "Oceanside", state: "California" },
  443: { city: "Baltimore", state: "Maryland" },
  458: { city: "Eugene", state: "Oregon" },
  469: { city: "Dallas", state: "Texas" },
  470: { city: "Atlanta", state: "Georgia" },
  475: { city: "Bridgeport", state: "Connecticut" },
  478: { city: "Macon", state: "Georgia" },
  479: { city: "Fort Smith", state: "Arkansas" },
  480: { city: "Mesa", state: "Arizona" },
  484: { city: "Allentown", state: "Pennsylvania" },
  501: { city: "Little Rock", state: "Arkansas" },
  502: { city: "Louisville", state: "Kentucky" },
  503: { city: "Portland", state: "Oregon" },
  504: { city: "New Orleans", state: "Louisiana" },
  505: { city: "Albuquerque", state: "New Mexico" },
  507: { city: "Rochester", state: "Minnesota" },
  508: { city: "Worcester", state: "Massachusetts" },
  509: { city: "Spokane", state: "Washington" },
  510: { city: "Oakland", state: "California" },
  512: { city: "Austin", state: "Texas" },
  513: { city: "Cincinnati", state: "Ohio" },
  515: { city: "Des Moines", state: "Iowa" },
  516: { city: "Hempstead", state: "New York" },
  517: { city: "Lansing", state: "Michigan" },
  518: { city: "Albany", state: "New York" },
  520: { city: "Tucson", state: "Arizona" },
  530: { city: "Redding", state: "California" },
  531: { city: "Omaha", state: "Nebraska" },
  534: { city: "Eau Claire", state: "Wisconsin" },
  539: { city: "Tulsa", state: "Oklahoma" },
  540: { city: "Roanoke", state: "Virginia" },
  541: { city: "Eugene", state: "Oregon" },
  551: { city: "Jersey City", state: "New Jersey" },
  559: { city: "Fresno", state: "California" },
  561: { city: "West Palm Beach", state: "Florida" },
  562: { city: "Long Beach", state: "California" },
  563: { city: "Davenport", state: "Iowa" },
  564: { city: "Vancouver", state: "Washington" },
  567: { city: "Toledo", state: "Ohio" },
  570: { city: "Scranton", state: "Pennsylvania" },
  571: { city: "Arlington", state: "Virginia" },
  573: { city: "Columbia", state: "Missouri" },
  574: { city: "South Bend", state: "Indiana" },
  575: { city: "Las Cruces", state: "New Mexico" },
  580: { city: "Lawton", state: "Oklahoma" },
  585: { city: "Rochester", state: "New York" },
  586: { city: "Warren", state: "Michigan" },
  601: { city: "Jackson", state: "Mississippi" },
  602: { city: "Phoenix", state: "Arizona" },
  603: { city: "Manchester", state: "New Hampshire" },
  605: { city: "Sioux Falls", state: "South Dakota" },
  606: { city: "Ashland", state: "Kentucky" },
  607: { city: "Binghamton", state: "New York" },
  608: { city: "Madison", state: "Wisconsin" },
  609: { city: "Trenton", state: "New Jersey" },
  610: { city: "Allentown", state: "Pennsylvania" },
  612: { city: "Minneapolis", state: "Minnesota" },
  614: { city: "Columbus", state: "Ohio" },
  615: { city: "Nashville", state: "Tennessee" },
  616: { city: "Grand Rapids", state: "Michigan" },
  617: { city: "Boston", state: "Massachusetts" },
  618: { city: "Belleville", state: "Illinois" },
  619: { city: "San Diego", state: "California" },
  620: { city: "Hutchinson", state: "Kansas" },
  623: { city: "Glendale", state: "Arizona" },
  626: { city: "Pasadena", state: "California" },
  628: { city: "San Francisco", state: "California" },
  629: { city: "Nashville", state: "Tennessee" },
  630: { city: "Aurora", state: "Illinois" },
  631: { city: "Brentwood", state: "New York" },
  636: { city: "O'Fallon", state: "Missouri" },
  641: { city: "Mason City", state: "Iowa" },
  646: { city: "New York City", state: "New York" },
  650: { city: "San Mateo", state: "California" },
  651: { city: "St. Paul", state: "Minnesota" },
  657: { city: "Anaheim", state: "California" },
  660: { city: "Sedalia", state: "Missouri" },
  661: { city: "Bakersfield", state: "California" },
  662: { city: "Tupelo", state: "Mississippi" },
  667: { city: "Baltimore", state: "Maryland" },
  669: { city: "San Jose", state: "California" },
  678: { city: "Atlanta", state: "Georgia" },
  681: { city: "Charleston", state: "West Virginia" },
  682: { city: "Fort Worth", state: "Texas" },
  701: { city: "Fargo", state: "North Dakota" },
  702: { city: "Las Vegas", state: "Nevada" },
  703: { city: "Alexandria", state: "Virginia" },
  704: { city: "Charlotte", state: "North Carolina" },
  706: { city: "Augusta", state: "Georgia" },
  707: { city: "Santa Rosa", state: "California" },
  708: { city: "Cicero", state: "Illinois" },
  712: { city: "Sioux City", state: "Iowa" },
  713: { city: "Houston", state: "Texas" },
  714: { city: "Anaheim", state: "California" },
  715: { city: "Eau Claire", state: "Wisconsin" },
  716: { city: "Buffalo", state: "New York" },
  717: { city: "Harrisburg", state: "Pennsylvania" },
  718: { city: "New York City", state: "New York" },
  719: { city: "Colorado Springs", state: "Colorado" },
  720: { city: "Denver", state: "Colorado" },
  724: { city: "New Castle", state: "Pennsylvania" },
  725: { city: "Las Vegas", state: "Nevada" },
  727: { city: "St. Petersburg", state: "Florida" },
  731: { city: "Jackson", state: "Tennessee" },
  732: { city: "Toms River", state: "New Jersey" },
  734: { city: "Ann Arbor", state: "Michigan" },
  737: { city: "Austin", state: "Texas" },
  740: { city: "Zanesville", state: "Ohio" },
  747: { city: "Burbank", state: "California" },
  754: { city: "Fort Lauderdale", state: "Florida" },
  757: { city: "Virginia Beach", state: "Virginia" },
  760: { city: "Oceanside", state: "California" },
  762: { city: "Columbus", state: "Georgia" },
  763: { city: "Brooklyn Park", state: "Minnesota" },
  765: { city: "Muncie", state: "Indiana" },
  769: { city: "Jackson", state: "Mississippi" },
  770: { city: "Roswell", state: "Georgia" },
  772: { city: "Port St. Lucie", state: "Florida" },
  773: { city: "Chicago", state: "Illinois" },
  774: { city: "Worcester", state: "Massachusetts" },
  775: { city: "Reno", state: "Nevada" },
  779: { city: "Rockford", state: "Illinois" },
  781: { city: "Lynn", state: "Massachusetts" },
  785: { city: "Topeka", state: "Kansas" },
  786: { city: "Miami", state: "Florida" },
  801: { city: "Salt Lake City", state: "Utah" },
  802: { city: "Burlington", state: "Vermont" },
  803: { city: "Columbia", state: "South Carolina" },
  804: { city: "Richmond", state: "Virginia" },
  805: { city: "Oxnard", state: "California" },
  806: { city: "Amarillo", state: "Texas" },
  808: { city: "Honolulu", state: "Hawaii" },
  810: { city: "Flint", state: "Michigan" },
  812: { city: "Evansville", state: "Indiana" },
  813: { city: "Tampa", state: "Florida" },
  814: { city: "Erie", state: "Pennsylvania" },
  815: { city: "Rockford", state: "Illinois" },
  816: { city: "Kansas City", state: "Missouri" },
  817: { city: "Fort Worth", state: "Texas" },
  818: { city: "Glendale", state: "California" },
  828: { city: "Asheville", state: "North Carolina" },
  830: { city: "New Braunfels", state: "Texas" },
  831: { city: "Salinas", state: "California" },
  832: { city: "Houston", state: "Texas" },
  843: { city: "Charleston", state: "South Carolina" },
  845: { city: "New City", state: "New York" },
  847: { city: "Elgin", state: "Illinois" },
  848: { city: "Toms River", state: "New Jersey" },
  850: { city: "Tallahassee", state: "Florida" },
  854: { city: "Charleston", state: "South Carolina" },
  856: { city: "Camden", state: "New Jersey" },
  857: { city: "Boston", state: "Massachusetts" },
  858: { city: "San Diego", state: "California" },
  859: { city: "Lexington", state: "Kentucky" },
  860: { city: "Hartford", state: "Connecticut" },
  862: { city: "Newark", state: "New Jersey" },
  863: { city: "Lakeland", state: "Florida" },
  864: { city: "Greenville", state: "South Carolina" },
  865: { city: "Knoxville", state: "Tennessee" },
  867: { city: "Whitehorse", state: "Yukon, Canada" },
  868: { city: "Port of Spain", state: "Trinidad and Tobago" },
  869: { city: "Basseterre", state: "Saint Kitts and Nevis" },
  870: { city: "Jonesboro", state: "Arkansas" },
  872: { city: "Chicago", state: "Illinois" },
  873: { city: "Gatineau", state: "Quebec, Canada" },
  876: { city: "Kingston", state: "Jamaica" },
  878: { city: "Pittsburgh", state: "Pennsylvania" },
  901: { city: "Memphis", state: "Tennessee" },
  902: { city: "Halifax", state: "Nova Scotia, Canada" },
  903: { city: "Tyler", state: "Texas" },
  904: { city: "Jacksonville", state: "Florida" },
  905: { city: "Mississauga", state: "Ontario, Canada" },
  906: { city: "Marquette", state: "Michigan" },
  907: { city: "Anchorage", state: "Alaska" },
  908: { city: "Elizabeth", state: "New Jersey" },
  909: { city: "San Bernardino", state: "California" },
  910: { city: "Fayetteville", state: "North Carolina" },
  912: { city: "Savannah", state: "Georgia" },
  913: { city: "Overland Park", state: "Kansas" },
  914: { city: "Yonkers", state: "New York" },
  915: { city: "El Paso", state: "Texas" },
  916: { city: "Sacramento", state: "California" },
  917: { city: "New York City", state: "New York" },
  918: { city: "Tulsa", state: "Oklahoma" },
  919: { city: "Raleigh", state: "North Carolina" },
  920: { city: "Green Bay", state: "Wisconsin" },
  925: { city: "Concord", state: "California" },
  928: { city: "Yuma", state: "Arizona" },
  929: { city: "New York City", state: "New York" },
  930: { city: "Bloomington", state: "Indiana" },
  931: { city: "Clarksville", state: "Tennessee" },
  935: { city: "San Diego", state: "California" },
  936: { city: "Conroe", state: "Texas" },
  937: { city: "Dayton", state: "Ohio" },
  938: { city: "Huntsville", state: "Alabama" },
  939: { city: "San Juan", state: "Puerto Rico" },
  940: { city: "Denton", state: "Texas" },
  941: { city: "Sarasota", state: "Florida" },
  947: { city: "Troy", state: "Michigan" },
  949: { city: "Irvine", state: "California" },
  951: { city: "Riverside", state: "California" },
  952: { city: "Bloomington", state: "Minnesota" },
  954: { city: "Fort Lauderdale", state: "Florida" },
  956: { city: "Laredo", state: "Texas" },
  959: { city: "Hartford", state: "Connecticut" },
  970: { city: "Fort Collins", state: "Colorado" },
  971: { city: "Portland", state: "Oregon" },
  972: { city: "Dallas", state: "Texas" },
  973: { city: "Newark", state: "New Jersey" },
  975: { city: "St. Louis", state: "Missouri" },
  978: { city: "Lowell", state: "Massachusetts" },
  979: { city: "College Station", state: "Texas" },
  980: { city: "Charlotte", state: "North Carolina" },
  984: { city: "Raleigh", state: "North Carolina" },
  985: { city: "Houma", state: "Louisiana" },
  986: { city: "Boise", state: "Idaho" },
  989: { city: "Saginaw", state: "Michigan" },
};

export function ExtractAreaCode(phoneNumber) {
  // Normalize the phone number by removing non-digit characters
  const cleaned = phoneNumber.replace(/[^0-9]/g, "");

  // Check if the cleaned number starts with '1' (country code for the US)
  const startsWithOne = cleaned.startsWith("1");

  // Extract the area code: skip the first digit if it starts with '1'
  const areaCode = startsWithOne ? cleaned.slice(1, 4) : cleaned.slice(0, 3);

  // Return the extracted area code
  let code = AreaCodes[areaCode];
  console.log("Area code ", code);
  return { areaCode: areaCode, city: code?.city, state: code?.state };
}
